[font]
size = 14.5

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[window]
# - { key: Subtract, mods: Control, action: DecreaseFontSize             }
opacity = 0.9
option_as_alt = "OnlyLeft"

# [keyboard]
# bindings = [{ key = "-", mods = "Control", action = "None" }]
