# theme = "tokyonight_modify"
theme = "catppuccin_modify"

[editor]
auto-format = true
auto-save = true
line-number = "relative"
color-modes = true
cursorline = true
cursorcolumn = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = [
    "version-control",
    "diagnostics",
    "file-encoding",
    "file-line-ending",
    "file-type",
    "position",
]

# separator = "|"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.indent-guides]
render = true
# character = "╎" # Some characters that work well: "▏","╎", "┆", "┊", "⸽"
character = "▏" # Some characters that work well: "▏","╎", "┆", "┊", "⸽"

[editor.lsp]
# better be a toggle
display-inlay-hints = true
# Show LSP messages in the status line
display-messages = true

[keys.normal]
# move line down
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
# move line up
A-k = [
    "extend_to_line_bounds",
    "delete_selection",
    "move_line_up",
    "paste_before",
]
H = ":buffer-next"
L = ":buffer-previous"
#esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
# c = ":buffer-close"
C-g = [":new", ":insert-output lazygit", ":redraw", "jump_backward"]
e = ":sh zellij run -f -x 10% -y 10% --width 80% --height 80% -- bash ~/.config/helix/yazi-picker.sh"
