theme = "tokyonight_modify"

[editor]
line-number = "relative"
color-modes = true
cursorline = true
cursorcolumn = true
auto-save = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏","╎", "┆", "┊", "⸽"

[editor.lsp]
display-inlay-hints = true

[keys.normal]
# move line down
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
# move line up
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
#esc = ["collapse_selection", "keep_primary_selection"]
