# Solidity
[[language]]
name = "solidity"
auto-format = false
scope = "source.sol"
injection-regex = "^(sol|solidity)$"
file-types = ["sol"]
comment-token = "//"
language-servers = ["solidity"]
formatter = { command = 'forge', args = ["fmt", "-r","-"], stdin = true }

[language-server.solidity]
command = "vscode-solidity-server"
args = ["--stdio"]

# Rust
[[language]]
name = "rust"
formatter = { command = "leptosfmt", args = ["--stdin", "--rustfmt"] }
 
# GO
[[language]]
name = "go"
auto-format = false
formatter = { command = "goimports" }
