# Solidity
[[language]]
name = "solidity"
auto-format = true
scope = "source.sol"
injection-regex = "^(sol|solidity)$"
file-types = ["sol"]
comment-token = "//"
language-servers = ["solidity"]
formatter = { command = 'bash', args = ["-c", "echo $FILENAME"], stdin = false }

[language-server.solidity]
command = "vscode-solidity-server"
args = ["--stdio"]

# Rust
[[language]]
name = "rust"
formatter = { command = "leptosfmt", args = ["--stdin", "--rustfmt"] }
