[[language]]
name = "solidity"
scope = "source.sol"
injection-regex = "(sol|solidity)"
file-types = ["sol"]
comment-token = "//"
indent = { tab-width = 4, unit = "  " }
language-server = { command = "solidity-language-server", args = ["--stdio"] }
formatter = {command = "forge", args = ["fmt", "-r", "-"]}
auto-format = true
