inherits = "catppuccin_frappe"
# Buffer line color
"ui.virtual.inlay-hint" = { fg = "#685370" }

# background
"ui.background" = {}
# Line number, selected color
"ui.linenr.selected" = "persianpink"

# Override colors in the palette:
[palette]
persianpink = "#FF77BB"
