inherits = "catppuccin_frappe"
# Buffer line color
# "ui.statusline.inactive" = { fg = "gray" }
# "ui.statusline" = { fg = "rosegold" }

# background
"ui.background" = {}
# Line number, selected color
"ui.linenr.selected" = "persianpink"

# "comment" = { fg = "grey-comment", modifiers = ["italic"] }

# Override colors in the palette:
[palette]
rosegold = "#b76e79"
lightslategray = '#708090'
persianpink = "#FF77BB"
lightmagenta = "#FF77FF"
white = "#ffffff"
bossanova = "#452859"
red = "#ff0000"
background_highlight = "#30374b"
grey-comment = "#685370"
