inherits = "tokyonight_storm"

# Buffer line color
"ui.statusline.inactive" = { fg = "gray" }
"ui.statusline" = { fg = "rosegold" }

# Line number, selected color
"ui.linenr" = "lightslategray"
"ui.linenr.selected" = "persianpink"
"ui.cursorline.primary" = { bg = "background_highlight" }
"ui.cursor.primary" = {fg="white", bg = "red"}

# Override colors in the palette:
[palette]
rosegold = "#b76e79"
lightslategray = '#708090'
persianpink = "#FF77BB"
lightmagenta = "#FF77FF"
white = "#ffffff"
bossanova = "#452859"
red = "#ff0000"
background_highlight = "#30374b"
